name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'Dojo.Net.csproj'

    defaults:
      run:
        working-directory: ./src

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal
