name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'Dojo.Net.csproj'

    defaults:
      run:
        working-directory: ./src

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore dependencies
      run: nuget restore $PROJECT

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build $PROJECT --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
